language: python

python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "2.7"
  - "pypy"
  - "pypy3"

install:
  - pip install --upgrade pip
  - pip install setuptools==42
  - pip install setuptools-scm==5
  - pip install -e .[dev]
  - pip install tox-travis

script:
  - tox
